apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  name: nvidia-gpu
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  displayName: nvidia-gpu
  description: ""
  enabled: true
  hardware:
    - identifier: nvidia.com/gpu
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule