apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cert-converter
  namespace: rag
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: convert
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              crt=$(oc get secret redis-ui-letsencrypt -o jsonpath='{.data.tls\.crt}')
              key=$(oc get secret redis-ui-letsencrypt -o jsonpath='{.data.tls\.key}')
              echo $crt | base64 -d > /tmp/certificate.pem
              echo $key | base64 -d > /tmp/key.pem
              
              oc create secret generic rec-ui-cert \
                --from-file=certificate=/tmp/certificate.pem \
                --from-file=key=/tmp/key.pem \
                --from-literal=name=cm \
                --dry-run=client -o yaml | oc apply -f -
