apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Operators/NodeFeatureDiscovery/aggregate
    repoURL: 'https://github.com/cmays20/OpenShift-Redis-AI-Demo.git'
    targetRevision: REVISION
  syncPolicy:
    automated:
      selfHeal: true